services:
  loadbalancer:
    build: .
    ports:
      - "8000:8000"
      - "2112:2112"
    depends_on:
      - backend1 
      - backend2
      - backend3
    networks:
      - lb-net
    tty: true
    stdin_open: true

  backend1:
    build: ${APP_PATH}
    environment:
      - APP_COLOR=#3498db
    volumes:
      - ${APP_PATH}:/app
      - /app/node_modules
    networks:
      - lb-net

  backend2:
    build: ${APP_PATH}
    environment:
      - APP_COLOR=#e74c3c
    volumes:
      - ${APP_PATH}:/app
      - /app/node_modules
    networks:
      - lb-net

  backend3:
    build: ${APP_PATH}
    environment:
      - APP_COLOR=#2ecc71
    volumes:
      - ${APP_PATH}:/app
      - /app/node_modules
    networks:
      - lb-net

networks:
  lb-net:
    driver: bridge